### ISSUE TITLE
Cannot serialize array of bytes to JSON array

### ISSUE THREAD

**Issue by plokhotnyuk** [sirthias/borer#49] opened 2019-07-29 10:44 UTC
It can be reproduced with v0.10.0:
```
scala> val jsonBytes = "[1,2,3]".getBytes
jsonBytes: Array[Byte] = Array(91, 49, 44, 50, 44, 51, 93)

scala> io.bullet.borer.Json.decode(jsonBytes).to[Array[Byte]].value
res0: Array[Byte] = Array(1, 2, 3)

scala> io.bullet.borer.Json.encode(res0).toByteArray
io.bullet.borer.Borer$Error$Unsupported: The JSON renderer doesn't support byte strings (Output.ToByteArray index 0)
  at io.bullet.borer.json.JsonRenderer.failUnsupported(JsonRenderer.scala:275)
  at io.bullet.borer.json.JsonRenderer.onBytes(JsonRenderer.scala:122)
  at io.bullet.borer.Writer.writeBytes(Writer.scala:65)
  at io.bullet.borer.Encoder$.$anonfun$forByteArray$1(Encoder.scala:107)
  at io.bullet.borer.Writer.write(Writer.scala:86)
  at io.bullet.borer.EncodingSetup$Impl.render(EncodingSetup.scala:190)
  at io.bullet.borer.EncodingSetup$Impl.result(EncodingSetup.scala:138)
  at io.bullet.borer.EncodingSetup$Impl.toByteArray(EncodingSetup.scala:117)
  ... 36 elided
```

**Comment by sirthias** [comment] 2019-07-29 12:07
Thank you, @plokhotnyuk, but this is a duplicate of https://github.com/sirthias/borer/issues/40, which was already closed by https://github.com/sirthias/borer/commit/212d781dbec98cd6a6b6dda70dbfe88c26fb1779.

**Comment by sirthias** [comment] 2019-07-29 12:08
The fix will be in 0.11.0, which will hopefully be released before the end of this week...

**Closed by sirthias** 2019-07-29 12:07 UTC

**Comment by plokhotnyuk** [comment] 2019-07-29 12:36
Ups... Sorry, I skipped searching before reporting...

**Comment by sirthias** [comment] 2019-07-29 12:36
No problem at all...
(Happens to me all the time! ;)

**Comment by plokhotnyuk** [comment] 2019-07-29 12:46
It happened when I revised FIXME comments in benchmarks of jsoniter-scala... 

Yet another asymmetric case when borer can parse a message with defined default values for fields but [cannot skip them during serialization](https://github.com/plokhotnyuk/jsoniter-scala/blob/03a265d8e7ba2459363f66da5c1b36712eb9eee4/jsoniter-scala-benchmark/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/benchmark/OpenRTBWriting.scala#L22)... Would it worth to rise a ticket?

**Comment by sirthias** [comment] 2019-07-29 12:46
Ah, yes. Thank you! I think that's worth a ticket.
